apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-traffic-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-traffic-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <fs-id>
